server:
  port: 0
spring:
  application:
    name: service-hello

eureka:
  client:
    service-url:
      defaultZone: http://peer1:12001/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int(65536)}